name: EntryTracker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r entryTracker/requirements.txt

      - name: Run unit tests
        run: |
          pip install pytest
          pytest entryTracker/tests

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t estiblass/entrytracker:latest .

  e2e_test:
    runs-on: ubuntu-latest
    needs: package
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: entrytrackerdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start docker-compose
        run: docker compose up -d

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -qf name=db) || echo "notfound")
            if [ "$STATUS" == "healthy" ]; then
              echo "MySQL is healthy"
              break
            fi
            echo "Waiting for MySQL to be healthy... (status: $STATUS)"
            sleep 5
          done

      - name: Run E2E test with curl
        run: curl http://localhost:5000

      - name: Stop docker-compose
        run: docker compose down

  push_image:
    runs-on: ubuntu-latest
    needs: e2e_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push estiblass/entrytracker:latest
